version: "3.3"

services:
  broker:
    image:  rabbitmq:3-management-alpine
    restart: always
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=lebremt
      - RABBITMQ_DEFAULT_PASS=celeries
    networks:
      samp-net:
        ipv4_address: 172.45.0.2      
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ttsapp
      - POSTGRES_USER=ttsuser
      - POSTGRES_PASSWORD=ttspassword
    networks:
      samp-net:
        ipv4_address: 172.45.0.3
  app:
    build: .
    restart: always
    environment:
      - ENVIRONMENT=production 
    command: /usr/bin/supervisord
    volumes:
      - .:/code
    ports:
      - 9000:9000
      - 4000:4000
    depends_on:
      - db
      - broker
    networks:
      samp-net:
        ipv4_address: 172.45.0.4

networks:
  ttsplatform-net:
    external: true