# Generated by Django 4.0.3 on 2022-04-09 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default='', max_length=256)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='IDLE', max_length=32)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
    ]
