# Generated by Django 4.0.3 on 2022-07-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmonitor',
            options={'ordering': ['-data']},
        ),
        migrations.AddField(
            model_name='taskmonitor',
            name='descricao',
            field=models.CharField(default='Carregando...', max_length=256),
        ),
    ]
